// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: o1pmstream/pm_pdsus.proto

package o1pmstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PDSUs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pdsu []*PDSUs_PDSU `protobuf:"bytes,1,rep,name=pdsu,proto3" json:"pdsu,omitempty"`
}

func (x *PDSUs) Reset() {
	*x = PDSUs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDSUs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDSUs) ProtoMessage() {}

func (x *PDSUs) ProtoReflect() protoreflect.Message {
	mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDSUs.ProtoReflect.Descriptor instead.
func (*PDSUs) Descriptor() ([]byte, []int) {
	return file_o1pmstream_pm_pdsus_proto_rawDescGZIP(), []int{0}
}

func (x *PDSUs) GetPdsu() []*PDSUs_PDSU {
	if x != nil {
		return x.Pdsu
	}
	return nil
}

type PDSUs_SubCounterIndexType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// One of a sub-counter index types.
	//
	// Types that are assignable to SubCounterIndexTypes:
	//	*PDSUs_SubCounterIndexType_Sum
	//	*PDSUs_SubCounterIndexType_BinIndex
	//	*PDSUs_SubCounterIndexType_QOS_5QI
	//	*PDSUs_SubCounterIndexType_QOS_QCI
	//	*PDSUs_SubCounterIndexType_Cause
	//	*PDSUs_SubCounterIndexType_StringIndex
	//	*PDSUs_SubCounterIndexType_Plmn
	//	*PDSUs_SubCounterIndexType_Snssai
	SubCounterIndexTypes isPDSUs_SubCounterIndexType_SubCounterIndexTypes `protobuf_oneof:"sub_counter_index_types"`
}

func (x *PDSUs_SubCounterIndexType) Reset() {
	*x = PDSUs_SubCounterIndexType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDSUs_SubCounterIndexType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDSUs_SubCounterIndexType) ProtoMessage() {}

func (x *PDSUs_SubCounterIndexType) ProtoReflect() protoreflect.Message {
	mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDSUs_SubCounterIndexType.ProtoReflect.Descriptor instead.
func (*PDSUs_SubCounterIndexType) Descriptor() ([]byte, []int) {
	return file_o1pmstream_pm_pdsus_proto_rawDescGZIP(), []int{0, 0}
}

func (m *PDSUs_SubCounterIndexType) GetSubCounterIndexTypes() isPDSUs_SubCounterIndexType_SubCounterIndexTypes {
	if m != nil {
		return m.SubCounterIndexTypes
	}
	return nil
}

func (x *PDSUs_SubCounterIndexType) GetSum() string {
	if x, ok := x.GetSubCounterIndexTypes().(*PDSUs_SubCounterIndexType_Sum); ok {
		return x.Sum
	}
	return ""
}

func (x *PDSUs_SubCounterIndexType) GetBinIndex() int32 {
	if x, ok := x.GetSubCounterIndexTypes().(*PDSUs_SubCounterIndexType_BinIndex); ok {
		return x.BinIndex
	}
	return 0
}

func (x *PDSUs_SubCounterIndexType) GetQOS_5QI() int32 {
	if x, ok := x.GetSubCounterIndexTypes().(*PDSUs_SubCounterIndexType_QOS_5QI); ok {
		return x.QOS_5QI
	}
	return 0
}

func (x *PDSUs_SubCounterIndexType) GetQOS_QCI() int32 {
	if x, ok := x.GetSubCounterIndexTypes().(*PDSUs_SubCounterIndexType_QOS_QCI); ok {
		return x.QOS_QCI
	}
	return 0
}

func (x *PDSUs_SubCounterIndexType) GetCause() int32 {
	if x, ok := x.GetSubCounterIndexTypes().(*PDSUs_SubCounterIndexType_Cause); ok {
		return x.Cause
	}
	return 0
}

func (x *PDSUs_SubCounterIndexType) GetStringIndex() string {
	if x, ok := x.GetSubCounterIndexTypes().(*PDSUs_SubCounterIndexType_StringIndex); ok {
		return x.StringIndex
	}
	return ""
}

func (x *PDSUs_SubCounterIndexType) GetPlmn() []byte {
	if x, ok := x.GetSubCounterIndexTypes().(*PDSUs_SubCounterIndexType_Plmn); ok {
		return x.Plmn
	}
	return nil
}

func (x *PDSUs_SubCounterIndexType) GetSnssai() *PDSUs_SubCounterIndexType_SNSSAI {
	if x, ok := x.GetSubCounterIndexTypes().(*PDSUs_SubCounterIndexType_Snssai); ok {
		return x.Snssai
	}
	return nil
}

type isPDSUs_SubCounterIndexType_SubCounterIndexTypes interface {
	isPDSUs_SubCounterIndexType_SubCounterIndexTypes()
}

type PDSUs_SubCounterIndexType_Sum struct {
	Sum string `protobuf:"bytes,1,opt,name=sum,proto3,oneof"` //Static value "SUM" to be specified
}

type PDSUs_SubCounterIndexType_BinIndex struct {
	BinIndex int32 `protobuf:"varint,2,opt,name=bin_index,json=binIndex,proto3,oneof"`
}

type PDSUs_SubCounterIndexType_QOS_5QI struct {
	QOS_5QI int32 `protobuf:"varint,3,opt,name=qOS_5QI,json=qOS5QI,proto3,oneof"`
}

type PDSUs_SubCounterIndexType_QOS_QCI struct {
	QOS_QCI int32 `protobuf:"varint,4,opt,name=qOS_QCI,json=qOSQCI,proto3,oneof"`
}

type PDSUs_SubCounterIndexType_Cause struct {
	Cause int32 `protobuf:"varint,5,opt,name=cause,proto3,oneof"`
}

type PDSUs_SubCounterIndexType_StringIndex struct {
	StringIndex string `protobuf:"bytes,6,opt,name=string_index,json=stringIndex,proto3,oneof"`
}

type PDSUs_SubCounterIndexType_Plmn struct {
	Plmn []byte `protobuf:"bytes,7,opt,name=plmn,proto3,oneof"`
}

type PDSUs_SubCounterIndexType_Snssai struct {
	Snssai *PDSUs_SubCounterIndexType_SNSSAI `protobuf:"bytes,8,opt,name=snssai,proto3,oneof"`
}

func (*PDSUs_SubCounterIndexType_Sum) isPDSUs_SubCounterIndexType_SubCounterIndexTypes() {}

func (*PDSUs_SubCounterIndexType_BinIndex) isPDSUs_SubCounterIndexType_SubCounterIndexTypes() {}

func (*PDSUs_SubCounterIndexType_QOS_5QI) isPDSUs_SubCounterIndexType_SubCounterIndexTypes() {}

func (*PDSUs_SubCounterIndexType_QOS_QCI) isPDSUs_SubCounterIndexType_SubCounterIndexTypes() {}

func (*PDSUs_SubCounterIndexType_Cause) isPDSUs_SubCounterIndexType_SubCounterIndexTypes() {}

func (*PDSUs_SubCounterIndexType_StringIndex) isPDSUs_SubCounterIndexType_SubCounterIndexTypes() {}

func (*PDSUs_SubCounterIndexType_Plmn) isPDSUs_SubCounterIndexType_SubCounterIndexTypes() {}

func (*PDSUs_SubCounterIndexType_Snssai) isPDSUs_SubCounterIndexType_SubCounterIndexTypes() {}

type PDSUs_MeasValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//One of Measurement Value types.
	//
	// Types that are assignable to MeasValueTypes:
	//	*PDSUs_MeasValue_IntegerValue
	//	*PDSUs_MeasValue_RealValue
	//	*PDSUs_MeasValue_StringValue
	//	*PDSUs_MeasValue_SubCounters
	MeasValueTypes isPDSUs_MeasValue_MeasValueTypes `protobuf_oneof:"meas_value_types"`
}

func (x *PDSUs_MeasValue) Reset() {
	*x = PDSUs_MeasValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDSUs_MeasValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDSUs_MeasValue) ProtoMessage() {}

func (x *PDSUs_MeasValue) ProtoReflect() protoreflect.Message {
	mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDSUs_MeasValue.ProtoReflect.Descriptor instead.
func (*PDSUs_MeasValue) Descriptor() ([]byte, []int) {
	return file_o1pmstream_pm_pdsus_proto_rawDescGZIP(), []int{0, 1}
}

func (m *PDSUs_MeasValue) GetMeasValueTypes() isPDSUs_MeasValue_MeasValueTypes {
	if m != nil {
		return m.MeasValueTypes
	}
	return nil
}

func (x *PDSUs_MeasValue) GetIntegerValue() int64 {
	if x, ok := x.GetMeasValueTypes().(*PDSUs_MeasValue_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (x *PDSUs_MeasValue) GetRealValue() float64 {
	if x, ok := x.GetMeasValueTypes().(*PDSUs_MeasValue_RealValue); ok {
		return x.RealValue
	}
	return 0
}

func (x *PDSUs_MeasValue) GetStringValue() string {
	if x, ok := x.GetMeasValueTypes().(*PDSUs_MeasValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *PDSUs_MeasValue) GetSubCounters() *PDSUs_SubCounterListType {
	if x, ok := x.GetMeasValueTypes().(*PDSUs_MeasValue_SubCounters); ok {
		return x.SubCounters
	}
	return nil
}

type isPDSUs_MeasValue_MeasValueTypes interface {
	isPDSUs_MeasValue_MeasValueTypes()
}

type PDSUs_MeasValue_IntegerValue struct {
	// Represents a integer value.
	IntegerValue int64 `protobuf:"varint,1,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type PDSUs_MeasValue_RealValue struct {
	// Represents a real value.
	RealValue float64 `protobuf:"fixed64,2,opt,name=real_value,json=realValue,proto3,oneof"`
}

type PDSUs_MeasValue_StringValue struct {
	// Represents a string value.
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type PDSUs_MeasValue_SubCounters struct {
	// Represents a subCounters value.
	SubCounters *PDSUs_SubCounterListType `protobuf:"bytes,4,opt,name=sub_counters,json=subCounters,proto3,oneof"` // allow extension in futher version
}

func (*PDSUs_MeasValue_IntegerValue) isPDSUs_MeasValue_MeasValueTypes() {}

func (*PDSUs_MeasValue_RealValue) isPDSUs_MeasValue_MeasValueTypes() {}

func (*PDSUs_MeasValue_StringValue) isPDSUs_MeasValue_MeasValueTypes() {}

func (*PDSUs_MeasValue_SubCounters) isPDSUs_MeasValue_MeasValueTypes() {}

type PDSUs_SubCounterListType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubCounterIndex *PDSUs_SubCounterIndexType `protobuf:"bytes,1,opt,name=sub_counter_index,json=subCounterIndex,proto3" json:"sub_counter_index,omitempty"`
	SubCounterValue *PDSUs_MeasValue           `protobuf:"bytes,2,opt,name=sub_counter_value,json=subCounterValue,proto3" json:"sub_counter_value,omitempty"`
}

func (x *PDSUs_SubCounterListType) Reset() {
	*x = PDSUs_SubCounterListType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDSUs_SubCounterListType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDSUs_SubCounterListType) ProtoMessage() {}

func (x *PDSUs_SubCounterListType) ProtoReflect() protoreflect.Message {
	mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDSUs_SubCounterListType.ProtoReflect.Descriptor instead.
func (*PDSUs_SubCounterListType) Descriptor() ([]byte, []int) {
	return file_o1pmstream_pm_pdsus_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PDSUs_SubCounterListType) GetSubCounterIndex() *PDSUs_SubCounterIndexType {
	if x != nil {
		return x.SubCounterIndex
	}
	return nil
}

func (x *PDSUs_SubCounterListType) GetSubCounterValue() *PDSUs_MeasValue {
	if x != nil {
		return x.SubCounterValue
	}
	return nil
}

type PDSUs_PDSU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId                  int64                  `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	GranularityPeriodEndTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=granularity_period_end_time,json=granularityPeriodEndTime,proto3" json:"granularity_period_end_time,omitempty"`
	StandardizedMeasResults   []*PDSUs_MeasValue     `protobuf:"bytes,3,rep,name=standardized_meas_results,json=standardizedMeasResults,proto3" json:"standardized_meas_results,omitempty"`
	VendorSpecificMeasResults []*PDSUs_MeasValue     `protobuf:"bytes,4,rep,name=vendor_specific_meas_results,json=vendorSpecificMeasResults,proto3" json:"vendor_specific_meas_results,omitempty"`
}

func (x *PDSUs_PDSU) Reset() {
	*x = PDSUs_PDSU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDSUs_PDSU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDSUs_PDSU) ProtoMessage() {}

func (x *PDSUs_PDSU) ProtoReflect() protoreflect.Message {
	mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDSUs_PDSU.ProtoReflect.Descriptor instead.
func (*PDSUs_PDSU) Descriptor() ([]byte, []int) {
	return file_o1pmstream_pm_pdsus_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PDSUs_PDSU) GetStreamId() int64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *PDSUs_PDSU) GetGranularityPeriodEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.GranularityPeriodEndTime
	}
	return nil
}

func (x *PDSUs_PDSU) GetStandardizedMeasResults() []*PDSUs_MeasValue {
	if x != nil {
		return x.StandardizedMeasResults
	}
	return nil
}

func (x *PDSUs_PDSU) GetVendorSpecificMeasResults() []*PDSUs_MeasValue {
	if x != nil {
		return x.VendorSpecificMeasResults
	}
	return nil
}

type PDSUs_SubCounterIndexType_SNSSAI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sst []byte `protobuf:"bytes,1,opt,name=sst,proto3" json:"sst,omitempty"`
	Sd  []byte `protobuf:"bytes,2,opt,name=sd,proto3" json:"sd,omitempty"`
}

func (x *PDSUs_SubCounterIndexType_SNSSAI) Reset() {
	*x = PDSUs_SubCounterIndexType_SNSSAI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDSUs_SubCounterIndexType_SNSSAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDSUs_SubCounterIndexType_SNSSAI) ProtoMessage() {}

func (x *PDSUs_SubCounterIndexType_SNSSAI) ProtoReflect() protoreflect.Message {
	mi := &file_o1pmstream_pm_pdsus_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDSUs_SubCounterIndexType_SNSSAI.ProtoReflect.Descriptor instead.
func (*PDSUs_SubCounterIndexType_SNSSAI) Descriptor() ([]byte, []int) {
	return file_o1pmstream_pm_pdsus_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PDSUs_SubCounterIndexType_SNSSAI) GetSst() []byte {
	if x != nil {
		return x.Sst
	}
	return nil
}

func (x *PDSUs_SubCounterIndexType_SNSSAI) GetSd() []byte {
	if x != nil {
		return x.Sd
	}
	return nil
}

var File_o1pmstream_pm_pdsus_proto protoreflect.FileDescriptor

var file_o1pmstream_pm_pdsus_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6f, 0x31, 0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x70, 0x6d, 0x5f,
	0x70, 0x64, 0x73, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x31, 0x70,
	0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x08, 0x0a, 0x05, 0x50, 0x44, 0x53, 0x55, 0x73, 0x12,
	0x2a, 0x0a, 0x04, 0x70, 0x64, 0x73, 0x75, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6f, 0x31, 0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x50, 0x44, 0x53, 0x55, 0x73,
	0x2e, 0x50, 0x44, 0x53, 0x55, 0x52, 0x04, 0x70, 0x64, 0x73, 0x75, 0x1a, 0xe0, 0x02, 0x0a, 0x13,
	0x53, 0x75, 0x62, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x09, 0x62, 0x69, 0x6e, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x62, 0x69,
	0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x19, 0x0a, 0x07, 0x71, 0x4f, 0x53, 0x5f, 0x35, 0x51,
	0x49, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x71, 0x4f, 0x53, 0x35, 0x51,
	0x49, 0x12, 0x19, 0x0a, 0x07, 0x71, 0x4f, 0x53, 0x5f, 0x51, 0x43, 0x49, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x71, 0x4f, 0x53, 0x51, 0x43, 0x49, 0x12, 0x16, 0x0a, 0x05,
	0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x63,
	0x61, 0x75, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x04, 0x70, 0x6c, 0x6d,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6c, 0x6d, 0x6e, 0x12,
	0x46, 0x0a, 0x06, 0x73, 0x6e, 0x73, 0x73, 0x61, 0x69, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2c, 0x2e, 0x6f, 0x31, 0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x50, 0x44, 0x53,
	0x55, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x53, 0x4e, 0x53, 0x53, 0x41, 0x49, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x6e, 0x73, 0x73, 0x61, 0x69, 0x1a, 0x2a, 0x0a, 0x06, 0x53, 0x4e, 0x53, 0x53, 0x41,
	0x49, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x73, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x02, 0x73, 0x64, 0x42, 0x19, 0x0a, 0x17, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0xd7,
	0x01, 0x0a, 0x09, 0x4d, 0x65, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0d,
	0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x73, 0x75, 0x62,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x6f, 0x31, 0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x50, 0x44, 0x53,
	0x55, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x42, 0x12, 0x0a, 0x10, 0x6d, 0x65, 0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0xb0, 0x01, 0x0a, 0x12, 0x53, 0x75, 0x62,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x51, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x31, 0x70,
	0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x50, 0x44, 0x53, 0x55, 0x73, 0x2e, 0x53, 0x75,
	0x62, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x47, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6f, 0x31, 0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x50, 0x44, 0x53, 0x55, 0x73,
	0x2e, 0x4d, 0x65, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0xb5, 0x02, 0x0a, 0x04,
	0x50, 0x44, 0x53, 0x55, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x12, 0x59, 0x0a, 0x1b, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79,
	0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x18, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x57, 0x0a, 0x19,
	0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x61,
	0x73, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6f, 0x31, 0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x50, 0x44, 0x53,
	0x55, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x17, 0x73, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x69, 0x7a, 0x65, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x5c, 0x0a, 0x1c, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x61, 0x73, 0x5f, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x31,
	0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x50, 0x44, 0x53, 0x55, 0x73, 0x2e, 0x4d,
	0x65, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x19, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x4d, 0x65, 0x61, 0x73, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x32, 0x49, 0x0a, 0x08, 0x50, 0x4d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x3d, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x4d, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x11, 0x2e, 0x6f, 0x31, 0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x50, 0x44, 0x53,
	0x55, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x1d,
	0x5a, 0x1b, 0x6d, 0x61, 0x76, 0x65, 0x6e, 0x69, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x31,
	0x70, 0x6d, 0x2f, 0x6f, 0x31, 0x70, 0x6d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_o1pmstream_pm_pdsus_proto_rawDescOnce sync.Once
	file_o1pmstream_pm_pdsus_proto_rawDescData = file_o1pmstream_pm_pdsus_proto_rawDesc
)

func file_o1pmstream_pm_pdsus_proto_rawDescGZIP() []byte {
	file_o1pmstream_pm_pdsus_proto_rawDescOnce.Do(func() {
		file_o1pmstream_pm_pdsus_proto_rawDescData = protoimpl.X.CompressGZIP(file_o1pmstream_pm_pdsus_proto_rawDescData)
	})
	return file_o1pmstream_pm_pdsus_proto_rawDescData
}

var file_o1pmstream_pm_pdsus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_o1pmstream_pm_pdsus_proto_goTypes = []interface{}{
	(*PDSUs)(nil),                            // 0: o1pmstream.PDSUs
	(*PDSUs_SubCounterIndexType)(nil),        // 1: o1pmstream.PDSUs.SubCounterIndexType
	(*PDSUs_MeasValue)(nil),                  // 2: o1pmstream.PDSUs.MeasValue
	(*PDSUs_SubCounterListType)(nil),         // 3: o1pmstream.PDSUs.SubCounterListType
	(*PDSUs_PDSU)(nil),                       // 4: o1pmstream.PDSUs.PDSU
	(*PDSUs_SubCounterIndexType_SNSSAI)(nil), // 5: o1pmstream.PDSUs.SubCounterIndexType.SNSSAI
	(*timestamppb.Timestamp)(nil),            // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 7: google.protobuf.Empty
}
var file_o1pmstream_pm_pdsus_proto_depIdxs = []int32{
	4, // 0: o1pmstream.PDSUs.pdsu:type_name -> o1pmstream.PDSUs.PDSU
	5, // 1: o1pmstream.PDSUs.SubCounterIndexType.snssai:type_name -> o1pmstream.PDSUs.SubCounterIndexType.SNSSAI
	3, // 2: o1pmstream.PDSUs.MeasValue.sub_counters:type_name -> o1pmstream.PDSUs.SubCounterListType
	1, // 3: o1pmstream.PDSUs.SubCounterListType.sub_counter_index:type_name -> o1pmstream.PDSUs.SubCounterIndexType
	2, // 4: o1pmstream.PDSUs.SubCounterListType.sub_counter_value:type_name -> o1pmstream.PDSUs.MeasValue
	6, // 5: o1pmstream.PDSUs.PDSU.granularity_period_end_time:type_name -> google.protobuf.Timestamp
	2, // 6: o1pmstream.PDSUs.PDSU.standardized_meas_results:type_name -> o1pmstream.PDSUs.MeasValue
	2, // 7: o1pmstream.PDSUs.PDSU.vendor_specific_meas_results:type_name -> o1pmstream.PDSUs.MeasValue
	0, // 8: o1pmstream.PMStream.StreamPMData:input_type -> o1pmstream.PDSUs
	7, // 9: o1pmstream.PMStream.StreamPMData:output_type -> google.protobuf.Empty
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_o1pmstream_pm_pdsus_proto_init() }
func file_o1pmstream_pm_pdsus_proto_init() {
	if File_o1pmstream_pm_pdsus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_o1pmstream_pm_pdsus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDSUs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o1pmstream_pm_pdsus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDSUs_SubCounterIndexType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o1pmstream_pm_pdsus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDSUs_MeasValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o1pmstream_pm_pdsus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDSUs_SubCounterListType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o1pmstream_pm_pdsus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDSUs_PDSU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o1pmstream_pm_pdsus_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDSUs_SubCounterIndexType_SNSSAI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_o1pmstream_pm_pdsus_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PDSUs_SubCounterIndexType_Sum)(nil),
		(*PDSUs_SubCounterIndexType_BinIndex)(nil),
		(*PDSUs_SubCounterIndexType_QOS_5QI)(nil),
		(*PDSUs_SubCounterIndexType_QOS_QCI)(nil),
		(*PDSUs_SubCounterIndexType_Cause)(nil),
		(*PDSUs_SubCounterIndexType_StringIndex)(nil),
		(*PDSUs_SubCounterIndexType_Plmn)(nil),
		(*PDSUs_SubCounterIndexType_Snssai)(nil),
	}
	file_o1pmstream_pm_pdsus_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*PDSUs_MeasValue_IntegerValue)(nil),
		(*PDSUs_MeasValue_RealValue)(nil),
		(*PDSUs_MeasValue_StringValue)(nil),
		(*PDSUs_MeasValue_SubCounters)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_o1pmstream_pm_pdsus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_o1pmstream_pm_pdsus_proto_goTypes,
		DependencyIndexes: file_o1pmstream_pm_pdsus_proto_depIdxs,
		MessageInfos:      file_o1pmstream_pm_pdsus_proto_msgTypes,
	}.Build()
	File_o1pmstream_pm_pdsus_proto = out.File
	file_o1pmstream_pm_pdsus_proto_rawDesc = nil
	file_o1pmstream_pm_pdsus_proto_goTypes = nil
	file_o1pmstream_pm_pdsus_proto_depIdxs = nil
}
